### PR TITLE
bug fix video overflow

### LINKED ISSUE #145: 🐛 Video on consulting page over flowing
Cc: @lukecookssw @ozairashfaqueSSW @kevinpho2022 @pierssinclairssw @adamcogan 

To myself, 

### Describe the Bug
Video on consulting page is over flowing 

### To Reproduce
1. Go to [SSW staging website](https://frontdoorstaging.z01.azurefd.net/ssw/consulting/angular/)
2. See error

### Expected Behavior
Video is contained to the appropriate div

### Tasks
- [x] Investigate the issue causing overflowing
- [x] Fix the bug

### Environment
 - Device: PC Browser
 - Browser: All

### Screenshots
image
**Figure: Capture of video sizing error**

Thanks!

### PR DESCRIPTION
**Pull request by ozair-ashfaque**
resolves #145 

- Fixed the video overflow
- Fixed the styling of containers
- Fixed the top bar

D9C2BDD3-5392-426E-862F-47AFCF3AA712
**Figure: Video is not overflowed**

### CODE REVIEW

File: src/templates/consulting/components/benefits/index.tsx [hunk 1]
```diff
@@ -1,61 +1,51 @@
...
-                </div>
+  return (
+    <section className="container">
+      <a id="more" />
+      <article className="main-container">
+        <MDXRenderer>{markdownContent}</MDXRenderer>
 
-                {rule && (
-                    <p>
-                        Have a look at{' '}
```
Comment (lukecookssw) [inline src/templates/consulting/components/benefits/index.tsx:49]: remove the {' '} and use CSS margin-left on the anchor tag if you need to create some space.

File: src/templates/consulting/components/benefits/index.tsx [hunk 2]
```diff
@@ -1,61 +1,51 @@
...
+              <article className="benefitDesc">{description}</article>
             </article>
-        </section>
-    );
+          ))}
+        </div>
+
+        {rule && (
+          <p>
+            Have a look at{" "}
```
Comment (lukecookssw) [inline src/templates/consulting/components/benefits/index.tsx:39]: remove the {' '} and use CSS margin-left on the anchor tag if you need to create some space.

**Review by lukecookssw — CHANGES_REQUESTED** [review]

**Review by lukecookssw — APPROVED** [review]
